### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hackathons-backend#31]
The goal is to create an admin dashboard that replaces Airtable. The Airtable dashboard currently serves the following purposes:

```[tasklist]
### Tasks
- [ ] https://github.com/hackclub/hackathons-backend/issues/32
- [ ] https://github.com/hackclub/hackathons-backend/issues/33
- [ ] https://github.com/hackclub/hackathons-backend/issues/34
- [ ] https://github.com/hackclub/hackathons-backend/issues/35
- [ ] https://github.com/hackclub/hackathons-backend/issues/29
```

The dashboard needs to be authenticated (https://github.com/hackclub/hackathons-backend/issues/29) and authorized to just admins

I'm thinking it's probably best to scope the admin dashboard routes to prevent future path collision (in case the front end gets moved onto Rails too). Maybe such something as `/dashboard/...` or `/admin/...`
